ARG SCHEME=chibi
ARG IMAGE=chibi:head
FROM docker.io/schemers/${IMAGE}
RUN apt-get update && apt-get install -y \
    build-essential \
    make \
    libffi-dev \
    ca-certificates \
    git \
    pandoc \
    chicken-bin
RUN chicken-install r7rs
ENV PATH=${PATH}:/usr/local-other/bin
ARG SCHEME=chibi
ENV COMPILE_R7RS=${SCHEME}
COPY --from=local-build-compile-r7rs /opt/compile-r7rs /opt/compile-r7rs
ENV PATH=/opt/compile-r7rs:${PATH}
