(define-library
  (libs data)
  (import (scheme base)
          (scheme write)
          (scheme file)
          (scheme process-context)
          (srfi 170)
          (libs util))
  (export data)
  (include "data.scm"))
